version: '3'
services:
  test-postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Samsunggalaxyy1
      - POSTGRES_DB=test
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  test-backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - PGHOST=localhost
      - PGUSER=postgres
      - PGPASSWORD=Samsunggalaxyy1
      - PGPORT=5432      
      - PGDATABASE=test
    depends_on:
      - test-postgres