version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Samsunggalaxyy1
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=Samsunggalaxyy1
      - PGPORT=5432
      - PGDATABASE=testpostgre
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=Samsunggalaxyy1
      - PGPORT=5432
      - PGDATABASE=testpostgre
    depends_on:
      - postgres