version: '3'
services:
  app:
    test-postgres:
      image: postgres:latest
      ports:
        - 5432:5432
      environment:
        - PGHOST=localhost
        - PGUSER=postgres
        - PGPASSWORD=Samsunggalaxyy1
        - PGPORT=5432      
        - PGDATABASE=test
      volumes:
        - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    test-backend:
      build: ./backend
      environment:
        - PGHOST=localhost
        - PGUSER=postgres
        - PGPASSWORD=Samsunggalaxyy1
        - PGPORT=5432      
        - PGDATABASE=test
      depends_on:
        - test-postgres